<a href="https://colab.research.google.com/github/SivaPanadi27/Telecom-Customer-Retention-ML-System/blob/main/Data%20Inspection%20%2B%20Insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Overview:

This project focuses on building a Machine Learning model to help telecom companies identify customers who are likely to churn.

Telecom companies provide services like:
*   Mobile calls
*   Internet/network data
*   SMS services
*   Broadband (Wi-Fi)
*   TV/cable bundles

These companies earn revenue through customer subscription plans such as monthly and yearly packages.

When a customer stops using the services or switches to another provider, it results in revenue loss for the company. This situation is known as customer churn.

The main objective of this project is to build a model that can predict churn early, so companies can take proactive actions (offers, support, better plans) to retain customers and reduce losses.

# Step-1: Data Collection

To train our machine learning models, we collected the dataset from Google Dataset Search.


The dataset used is the Telecom Churn Dataset, which contains information about customers and whether they have churned (left the service) or continued using the service.


The dataset is available in CSV (Comma Separated Values) format, which stores data in a tabular structure with rows and columns.

The dataset contains 7043 customer records and 52 features.

#Step-2: Data Loading

After collecting the dataset, the next step is to load it into the working environment so that it can be analyzed and processed.

In this project, the dataset is loaded using the Pandas library, which is widely used for data manipulation and analysis in Python. Pandas allows datasets to be stored in a DataFrame, a tabular structure consisting of rows and columns.

In [ ]:
#Code:
import pandas as pd
pd_df=pd.read_csv("Telecom_dataset.csv")
pd_df

,Age,Avg Monthly GB Download,Avg Monthly Long Distance Charges,Churn Category,Churn Reason,Churn Score,City,CLTV,Contract,Country,...,Tenure in Months,Total Charges,Total Extra Data Charges,Total Long Distance Charges,Total Refunds,Total Revenue,Under 30,Unlimited Data,Zip Code,Churn
0,72,4,19.44,NaN,NaN,51,San Mateo,4849,Two Year,United States,...,25,2191.15,0,486.00,0.0,2677.15,0,1,94403,0
1,27,59,45.62,NaN,NaN,27,Sutter Creek,3715,Month-to-Month,United States,...,35,3418.20,0,1596.70,0.0,5014.90,1,1,95685,0
2,59,0,16.07,NaN,NaN,59,Santa Cruz,5092,Month-to-Month,United States,...,46,851.20,0,739.22,0.0,1590.42,0,0,95064,0
3,25,27,0.00,NaN,NaN,49,Brea,2068,One Year,United States,...,27,1246.40,30,0.00,0.0,1276.40,1,0,92823,0
4,31,21,17.22,Dissatisfaction,Network reliability,88,San Jose,4026,One Year,United States,...,58,3563.80,0,998.76,0.0,4562.56,0,1,95117,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,33,12,10.67,NaN,NaN,53,Clayton,4847,Month-to-Month,United States,...,29,2878.75,0,309.43,0.0,3188.18,0,1,94517,0
7039,36,30,30.44,NaN,NaN,45,Nicolaus,5470,Two Year,United States,...,59,5655.45,0,1795.96,0.0,7451.41,0,1,95659,0
7040,57,24,4.51,NaN,NaN,74,Walnut Creek,4471,Two Year,United States,...,61,5175.30,0,275.11,0.0,5450.41,0,1,94596,0
7041,35,24,47.06,NaN,NaN,70,Valyermo,5445,Two Year,United States,...,30,1653.85,0,1411.80,0.0,3065.65,0,1,93563,0
7042,54,24,12.85,NaN,NaN,70,Rancho Cucamonga,5065,Two Year,United States,...,72,7998.80,70,925.20,0.0,8994.00,0,0,91701,0

#Step-3: Data Inspection



Data inspection is the process of examining the dataset to understand its structure, data types, missing values, and overall characteristics before performing further analysis or data cleaning.

This step helps identify potential issues in the dataset and provides an initial understanding of the data.

The following operations are performed during data inspection:

• Viewing sample records

• Checking dataset structure

• Understanding statistical summaries

• Identifying missing values

• Detecting duplicate rows

• Checking unique values in columns

In [ ]:
# 1)head(): It returns us the first five rows of the dataset. If we need any specific number of rows then we can mention it as head(number_of_required)
pd_df.head()

# 2)tail(): It returns us the last five rows of the dataset. if we need any specific number of rows then we can mention it as tail(number_of_required)
pd_df.tail()

# 3)Info():It tells us the what columns are presennt in the dataset their datatype and non-null count
pd_df.info()

# 4)Describe(): It gives us the stastical outcomes of the  numerical columns in dataset such as mean, std etc...
pd_df.describe()

# 5)Describe(): It gives us the stastical outcomes of the categorical columns in dataset
pd_df.describe(include='object')

# 6) Columns: It returns the columns present in the dataset
pd_df.columns

#7)Shape: It returns the matrix of rows and columns present in the dataset
pd_df.shape

# 8)value_counts:It is used on target variable to get to know whether the dataset is balanced or imblanced
pd_df["Churn"].value_counts()

# 9) Missing values
pd_df.isnull().sum()

# 10) Duplicate rows
pd_df.duplicated().sum()

# 11) Unique values in each column
pd_df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 52 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                7043 non-null   int64
 1   Avg Monthly GB Download            7043 non-null   int64
 2   Avg Monthly Long Distance Charges  7043 non-null   float64
 3   Churn Category                     1869 non-null   object
 4   Churn Reason                       1869 non-null   object
 5   Churn Score                        7043 non-null   int64
 6   City                               7043 non-null   object
 7   CLTV                               7043 non-null   int64
 8   Contract                           7043 non-null   object
 9   Country                            7043 non-null   object
 10  Customer ID                        7043 non-null   object
 11  Customer Status                    7043 non-null   object
 12  Dependents                         7043 non-null   int64
 13  Device Protection Plan             7043 non-null   int64
 14  Gender                             7043 non-null   object
 15  Internet Service                   7043 non-null   int64
 16  Internet Type                      5517 non-null   object
 17  Lat Long                           7043 non-null   object
 18  Latitude                           7043 non-null   float64
 19  Longitude                          7043 non-null   float64
 20  Married                            7043 non-null   int64
 21  Monthly Charge                     7043 non-null   float64
 22  Multiple Lines                     7043 non-null   int64
 23  Number of Dependents               7043 non-null   int64
 24  Number of Referrals                7043 non-null   int64
 25  Offer                              3166 non-null   object
 26  Online Backup                      7043 non-null   int64
 27  Online Security                    7043 non-null   int64
 28  Paperless Billing                  7043 non-null   int64
 29  Partner                            7043 non-null   int64
 30  Payment Method                     7043 non-null   object
 31  Phone Service                      7043 non-null   int64
 32  Population                         7043 non-null   int64
 33  Premium Tech Support               7043 non-null   int64
 34  Quarter                            7043 non-null   object
 35  Referred a Friend                  7043 non-null   int64
 36  Satisfaction Score                 7043 non-null   int64
 37  Senior Citizen                     7043 non-null   int64
 38  State                              7043 non-null   object
 39  Streaming Movies                   7043 non-null   int64
 40  Streaming Music                    7043 non-null   int64
 41  Streaming TV                       7043 non-null   int64
 42  Tenure in Months                   7043 non-null   int64
 43  Total Charges                      7043 non-null   float64
 44  Total Extra Data Charges           7043 non-null   int64
 45  Total Long Distance Charges        7043 non-null   float64
 46  Total Refunds                      7043 non-null   float64
 47  Total Revenue                      7043 non-null   float64
 48  Under 30                           7043 non-null   int64
 49  Unlimited Data                     7043 non-null   int64
 50  Zip Code                           7043 non-null   int64
 51  Churn                              7043 non-null   int64
dtypes: float64(8), int64(30), object(14)
memory usage: 2.8+ MB

Age                                    62
Avg Monthly GB Download                50
Avg Monthly Long Distance Charges    3584
Churn Category                          5
Churn Reason                           20
Churn Score                            81
City                                 1106
CLTV                                 3438
Contract                                3
Country                                 1
Customer ID                          7043
Customer Status                         3
Dependents                              2
Device Protection Plan                  2
Gender                                  2
Internet Service                        2
Internet Type                           3
Lat Long                             1679
Latitude                             1626
Longitude                            1625
Married                                 2
Monthly Charge                       1585
Multiple Lines                          2
Number of Dependents                   10
Number of Referrals                    12
Offer                                   5
Online Backup                           2
Online Security                         2
Paperless Billing                       2
Partner                                 2
Payment Method                          3
Phone Service                           2
Population                           1569
Premium Tech Support                    2
Quarter                                 1
Referred a Friend                       2
Satisfaction Score                      5
Senior Citizen                          2
State                                   1
Streaming Movies                        2
Streaming Music                         2
Streaming TV                            2
Tenure in Months                       72
Total Charges                        6540
Total Extra Data Charges               16
Total Long Distance Charges          6068
Total Refunds                         500
Total Revenue                        6975
Under 30                                2
Unlimited Data                          2
Zip Code                             1626
Churn                                   2
dtype: int64

#Insights from Data Inspection:

1) From the info() function we observed that:
  

* The dataset contains both numerical and categorical columns.
*  We have observed or understood that there are missing values present in Churn Category, Churn Reason, Internet Type, Offers

2) From the shape() function we observed that the dataset contains 7043 rows and 52 columns.

3) From isnull().sum() we found that missing values are present in the following columns:

   • Churn Category

   • Churn Reason

   • Internet Type

   • Offers

   The rest of the columns do not contain missing values.

4) From value_counts() on the Churn column we observed that:


*  The dataset is imbalanced.
*  The ratio between non-churn and churn customers is approximately 2.7 : 1.


5) From duplicated().sum() we have observed that the dataset contains 0 duplicate rows.

6) From the describe() function we obtained statistical summaries for:


*   Numerical columns such as:count, mean, median (50%), standard deviation, minimum, maximum, 25% and 75%.

* Categorical Columns: top, count,freq